name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn clean install

    - name: Sonar Analysis
      run: |
         mvn clean verify sonar:sonar \
         -Dsonar.projectKey=realstate \
         -Dsonar.projectName='realstate' \
         -Dsonar.host.url=http://hivemet.com:9000 \
         -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Docker build of the realstate app
      run: |
        docker build -t 78160/realstate-docker:1.0.0 .
        docker login -u 78160 -p ${{ secrets.DOCKER_PASS }}
        docker push 78160/realstate-docker:1.0.0

    # - name: Connect to Kubernetes Cluster and deploy the application
    #   run: |
    #      cd kubernetes
    #      export KUBECONFIG=admin.conf
    #      kubectl apply -f realstate_deploy.yaml 
    #      kubectl expose deployment realstate --port 9090 --type NodePort -n realstate
  
